version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    networks:
      - opensis_network
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - opensis_network
    ports:
      - '9100:9100'

  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - opensis_network
    ports:
      - '9093:9093'

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/plugins/oncall.yaml:/etc/grafana/provisioning/plugins/oncall.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-oncall-app
      - GF_FEATURE_TOGGLES_ENABLE=oncall
      - GF_SERVER_ROOT_URL=http://grafana:3000
      - GF_ONCALL_ALERTMANAGER_URL=http://alertmanager:9093
      # - GF_INSTALL_PLUGINS="grafana-oncall-app vv1.9.0"
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-oncall-app
      - GF_PLUGIN_GRAFANA_ONCALL_APP_STACK_ID=local
      - GF_PLUGIN_GRAFANA_ONCALL_APP_ONCALL_API_URL=http://oncall:9093
      - GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED=true
    networks:
      - opensis_network

networks:
  opensis_network:
    external: true

volumes:
  grafana-storage: {}
